name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.bump-version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Check commit message for keyword "docs"
        id: check-docs-commit
        run: echo ::set-output name=is_docs::$(if grep -q "docs" <<< "$(git log --format=%B -n 1)"; then echo "true"; else echo "false"; fi)
      - name: Bump version and push tag
        if: steps.check-docs-commit.outputs.is_docs != 'true'
        id: bump-version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          MAJOR_STRING_TOKEN: "release("
          MINOR_STRING_TOKEN: "feat("
          PATCH_STRING_TOKEN: "fix("
          DEFAULT_BUMP: minor
          
  build-and-publish:
    needs: generate-version
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Kafka Topic creator and publish to Docker Hub
        if: needs.generate-version.outputs.new_tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: egonzalezt/dev-kafka-topic-creator:latest, egonzalezt/dev-kafka-topic-creator:${{ needs.generate-version.outputs.new_tag }}
